# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmKingpinSample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealmKingpinSample
  
  pod 'kingpin', '~> 0.3'
  pod 'RealmSwift', '~> 1.0.2'

end
